<h1>Create an account</h1>

<form method="post">
    <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <?php echo $this->tag->textField(['name', "class" => "form-control"]) ?>
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">e-mail</label>
        <?php echo $this->tag->textField(['email', "class" => "form-control"]) ?>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">password</label>
        <?php echo $this->tag->passwordField(['password', 'class' => 'password form-control']); ?>
    </div>
    <div class="mb-3">
        <label for="role" class="form-label">role</label>
        <select class="form-control" name="role" id="role">
            <option value="user">user</option>
            <option value="admin">admin</option>
        </select>
    </div>
    <div class="mb-3">
        <?php echo $this->tag->submitButton(["Create", "class" => "btn btn-primary"]) ?>
    </div>
</form>

<?php
echo '<h1>';
echo $this->flashSession->output();
echo '</h1>';
?>