<h1>Edit</h1>
<form method="GET">
    <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <?php echo $this->tag->textField(['name', "class" => "form-control", 'value' => $user->name]) ?>
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">e-mail</label>
        <?php echo $this->tag->textField(['email', "class" => "form-control", 'value' => $user->email]) ?>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">password</label>
        <?php echo $this->tag->textField(['password', 'class' => 'password form-control', 'value' => $user->password]); ?>
    </div>
    <div class="mb-3">
        <label for="role" class="form-label">role</label>
        <select class="form-control" name="role" id="role">
            <option value="<?php echo $user->role ?>"><?php echo $user->role ?></option>
            <option value="user">user</option>
            <option value="admin">admin</option>
        </select>
    </div>
    <div class="mb-3">
        <?php echo $this->tag->submitButton(["edit", "class" => "btn btn-primary editBTN", 'name' => 'submit']) ?>
    </div>
</form>

<?php
echo '<h1>';
echo $this->flashSession->output();
echo '</h1>';
?>